apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: billing-service
spec:
  rules:
    - host: billing-service-stag
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: billing-service
                port:
                  name: http
